version: '{build}'
branches:
  except:
    - '/^wip/'
    - '/^blocked/'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: strawberry
      perl_version: 5.12.3.1
    - perl_type: strawberry
      perl_version: 5.16.3.3
    - perl_type: strawberry
      perl_version: 5.20.1.1
    - perl_type: cygwin

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - 'set AUTHOR_TESTING=1'

build: off

test_script:
  - '%perl% -S prove -lv'
